version: "3.9"

services:
  auth_service:
    build: ./backend/auth_service
    ports:
      - "8000:8000"
    env_file:
      - ./backend/auth_service/.env
    depends_on:
      - postgres_auth
    volumes:
      - ./backend/auth_service:/app
    command: [ "./wait-for-it.sh", "postgres_tracking:5432", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]

  postgres_auth:
    image: postgres:16
    env_file:
      - ./backend/auth_service/.env
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  telegram_bot:
    build: ./backend/telegram_bot
    env_file:
      - ./backend/telegram_bot/.env
    depends_on:
      - auth_service
    volumes:
      - ./backend/telegram_bot:/app

  tracking_service:
    build: ./backend/tracking_service
    ports:
      - "8001:8000"
    env_file:
      - ./backend/tracking_service/.env
    depends_on:
      - postgres_tracking
    volumes:
      - ./backend/tracking_service:/app
    command: [ "./wait-for-it.sh", "postgres_tracking:5432", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]

  postgres_tracking:
    image: postgres:16
    env_file:
      - ./backend/tracking_service/.env
    volumes:
      - tracking_pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  redis:
    image: redis:7
    container_name: redis_service
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  auth_pgdata:
  tracking_pgdata:
  redis_data:
