version: "3.9"

services:
  auth_service:
    build: ./backend/auth_service
    ports:
      - "8000:8000"
    env_file:
      - ./backend/auth_service/.env
    depends_on:
      - postgres_auth
    volumes:
      - ./backend/auth_service:/app

  postgres_auth:
    image: postgres:16
    env_file:
      - ./backend/auth_service/.env
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  telegram_bot:
    build: ./backend/telegram_bot
    env_file:
      - ./backend/telegram_bot/.env
    depends_on:
      - auth_service
    volumes:
      - ./backend/telegram_bot:/app

volumes:
  auth_pgdata:
